version: '3.6'
services:
  hasurademo:
    build:
      context: ./hasurademo
      dockerfile: Dockerfile
    image: hasurademo
    restart: always
    ports:
    - "8000:8000"
    depends_on:
    - "graphql-engine"
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    image: postgres
    restart: always
    ports:
    - "5432:5432"
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.3
    depends_on:
    - "postgres"
    restart: always
    ports:
    - "8080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey